<?php

namespace Mardraze\Ksef;

class ApiClient {
    protected $goApiUrl = 'http://127.0.0.1:3334';
    protected $token = '30AC53BF6313480A4C12278907E718C82086E19FD56DF3F43C889A28572FDD4A'; //generated by client
    protected $nip = '9781399259';
    protected $env = 'test'; //prod demo test

    public function __construct($options = array()){
        if(isset($options['goApiUrl'])){
            $this->goApiUrl = $options['goApiUrl'];
        }
        if(isset($options['token'])){
            $this->token = $options['token'];
        }
        if(isset($options['nip'])){
            $this->nip = $options['nip'];
        }
        if(isset($options['env'])){
            $this->env = $options['env'];
        }
    }

    public function sendInvoice($xml){
        $ch = curl_init();

        curl_setopt($ch, CURLOPT_URL, $this->goApiUrl.'/create-invoice');
        curl_setopt($ch, CURLOPT_POST, 1);
        curl_setopt($ch, CURLOPT_POSTFIELDS, $xml);
        curl_setopt($ch, CURLOPT_HTTPHEADER, array(
            'Content-Type: text/xml',
            'Content-Length: ' . strlen($xml),
            'x-token: '.$this->token,
            'x-nip: '.$this->nip,
            'x-env: '.$this->env
        ));
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);

        $server_output = curl_exec($ch);

        curl_close($ch);
        
        return json_decode($server_output, true);
    }
}
